export const ServerErrors = {
  ERR_AUTH_FORBIDDEN: 'ERR_AUTH_FORBIDDEN',
  ERR_INTERNAL_DB_FAILURE: 'ERR_INTERNAL_DB_FAILURE',
  ERR_INTERNAL_STRIPE_FAILURE: 'ERR_INTERNAL_STRIPE_FAILURE',
  ERR_INTERNAL_UNEXPECTED: 'ERR_INTERNAL_UNEXPECTED',
} as const;
