export const StripeErrors = {
  ERR_STRIPE_PAYMENT_FAILED: 'ERR_STRIPE_PAYMENT_FAILED',
  ERR_STRIPE_REQUIRES_ACTION: 'ERR_STRIPE_REQUIRES_ACTION',
  ERR_STRIPE_INTENT_NOT_FOUND: 'ERR_STRIPE_INTENT_NOT_FOUND',
  ERR_STRIPE_CONFIRMATION_REQUIRED: 'ERR_STRIPE_CONFIRMATION_REQUIRED',
  ERR_PAYMENT_INTENT_EXPIRED: 'ERR_PAYMENT_INTENT_EXPIRED',
} as const;
