export const ValidationErrors = {
  ERR_MISSING_REQUIRED_FIELD: 'ERR_MISSING_REQUIRED_FIELD',
  ERR_INVALID_PAYMENT_METHOD: 'ERR_INVALID_PAYMENT_METHOD',
  ERR_INVALID_CURRENCY: 'ERR_INVALID_CURRENCY',
  ERR_INVALID_COUNTRY: 'ERR_INVALID_COUNTRY',
  ERR_INVALID_ADDRESS: 'ERR_INVALID_ADDRESS',
  ERR_AMOUNT_BELOW_MINIMUM: 'ERR_AMOUNT_BELOW_MINIMUM',
  ERR_AMOUNT_ABOVE_MAXIMUM: 'ERR_AMOUNT_ABOVE_MAXIMUM',
  ERR_UNSUPPORTED_RECEIPT_COUNTRY: 'ERR_UNSUPPORTED_RECEIPT_COUNTRY',
} as const;
